-----------------QLDT----------------------
use QLDT
go

--Q2
SELECT HOTEN, LUONG*1.1 AS LUONGMOI
FROM GIAOVIEN GV

--Q4
SELECT HOTEN
FROM GIAOVIEN GV JOIN BOMON BM ON GV.MABM = BM.MABM 
JOIN KHOA K ON BM.MAKHOA = K.MAKHOA
WHERE K.TENKHOA = N'Công nghệ thông tin'

--Q6
SELECT *
FROM GIAOVIEN GV JOIN BOMON BM ON GV.MABM = BM.MABM

--Q8
SELECT *
FROM KHOA K JOIN GIAOVIEN GV ON K.TRUONGKHOA = GV.MAGV

--Q10
SELECT DT.MADT, DT.MACD, CD.TENCD, DT.GVCNDT, GV.HOTEN, GV.NGSINH, GV.DIACHI
FROM DETAI DT JOIN CHUDE CD ON DT.MACD = CD.MACD
JOIN GIAOVIEN GV ON DT.GVCNDT = GV.MAGV
WHERE DT.CAPQL = N'Thành phố'

--Q12
SELECT GV.HOTEN
FROM GIAOVIEN GV JOIN GIAOVIEN GVQL ON GV.GVQLCM = GVQL.MAGV
WHERE GVQL.HOTEN = N'Nguyễn Thanh Tùng'

--Q14
SELECT DT.MADT, DT.TENDT, DT.GVCNDT, GV.HOTEN
FROM DETAI DT JOIN GIAOVIEN GV ON DT.GVCNDT = GV.MAGV
JOIN CHUDE CD ON DT.MACD = CD.MACD
WHERE CD.TENCD = N'Quản lý giáo dục'

--Q16
SELECT GV.HOTEN, GVQL.HOTEN AS GVQL
FROM GIAOVIEN GV join GIAOVIEN GVQL on GV.GVQLCM = GVQL.MAGV

--Q18
SELECT GV.HOTEN
FROM GIAOVIEN GV
WHERE GV.MABM = (
	SELECT MABM 
	FROM GIAOVIEN GV2 
	WHERE GV2.HOTEN = N'Trần Trà Hương') 
AND NOT GV.HOTEN = N'Trần Trà Hương'

--Q20
SELECT GV.HOTEN
FROM GIAOVIEN GV
WHERE GV.MAGV IN (
	SELECT DISTINCT TRUONGKHOA
	FROM KHOA)
AND GV.MAGV IN (
	SELECT DISTINCT TRUONGBM
	FROM BOMON)

--Q22
SELECT TRUONGKHOA
FROM KHOA K
WHERE K.TRUONGKHOA IN (
	SELECT DISTINCT GVCNDT
	FROM DETAI)

--Q24
SELECT *
FROM GIAOVIEN GV
WHERE GV.MABM = (
	SELECT MABM 
	FROM GIAOVIEN GV2 
	WHERE GV2.MAGV = '002')
AND NOT GV.MAGV = '002'

--Q26
SELECT HOTEN, LUONG
FROM GIAOVIEN

-----------------QLCB---------------------
use QLCB
go

--Q1
SELECT NV.MANV, NV.TEN, NV.DCHI, NV.DTHOAI
FROM NHANVIEN NV join KHANANG KN on NV.MANV = KN.MANV
WHERE KN.MALOAI = 'B747'

--Q2
SELECT CB.MACB, LB.NGAYDI
FROM CHUYENBAY CB join LICHBAY LB on CB.MACB = LB.MACB
WHERE CB.SBDI = 'DCA' AND datepart(hour, CB.GIODI) >= 14 AND datepart(hour, CB.GIODI) <= 18

--Q3
SELECT DISTINCT PC.MANV, NV.TEN
FROM NHANVIEN NV join PHANCONG PC on NV.MANV = PC.MANV
join CHUYENBAY CB on PC.MACB = CB.MACB
WHERE PC.MACB=100 AND CB.SBDI = 'SLC'

--Q4
SELECT DISTINCT LB.MALOAI, LB.SOHIEU
FROM LICHBAY LB join CHUYENBAY CB on LB.MACB = CB.MACB
WHERE CB.SBDI = 'MIA'

--Q5
SELECT DC.MACB, DC.NGAYDI, KH.TEN, KH.DCHI, KH.DTHOAI
FROM KHACHHANG KH join DATCHO DC on KH.MAKH = DC.MAKH
ORDER BY MACB ASC, DC.NGAYDI DESC

--Q6
SELECT PC.MACB, PC.NGAYDI, NV.TEN, NV.DCHI, NV.DTHOAI
FROM NHANVIEN NV join PHANCONG PC on NV.MANV = PC.MANV
ORDER BY MACB ASC, PC.NGAYDI DESC

--Q7
SELECT PC.MACB, PC.NGAYDI, PC.MANV, NV.TEN
FROM NHANVIEN NV join PHANCONG PC on NV.MANV = PC.MANV
join CHUYENBAY CB on PC.MACB = CB.MACB
WHERE CB.SBDEN = 'ORD'

--Q8
SELECT PC.MACB, PC.NGAYDI, PC.MANV 
FROM CHUYENBAY CB join PHANCONG PC on CB.MACB = PC.MACB
WHERE PC.MANV = 1001

--Q9
SELECT CB.MACB, CB.SBDI, CB.GIODI, CB.GIODEN, LB.NGAYDI
FROM CHUYENBAY CB join LICHBAY LB on CB.MACB = LB.MACB
WHERE CB.SBDEN = 'DEN'
ORDER BY LB.NGAYDI DESC, CB.SBDI ASC

--Q10
SELECT NV.TEN, LMB.HANGSX, LMB.MALOAI
FROM NHANVIEN NV join KHANANG KN on NV.MANV = KN.MANV
join LOAIMB LMB on KN.MALOAI = LMB.MALOAI

--Q11
SELECT NV.MANV, NV.TEN
FROM NHANVIEN NV join PHANCONG PC on NV.MANV = PC.MANV
WHERE PC.NGAYDI = '11/01/2000' AND PC.MACB = 100

--Q12
SELECT PC.MACB, NV.MANV, NV.TEN
FROM NHANVIEN NV join PHANCONG PC on NV.MANV = PC.MANV
join CHUYENBAY CB on PC.MACB = CB.MACB
WHERE PC.NGAYDI = '10/31/2000'
AND datepart(hour, CB.GIODI) = 20 AND datepart(minute, CB.GIODI) = 30
AND CB.SBDI = 'MIA'

--Q13
SELECT LB.MACB, LB.SOHIEU, LMB.MALOAI, LMB.HANGSX
FROM NHANVIEN NV join PHANCONG PC on NV.MANV = PC.MANV
join LICHBAY LB on PC.MACB = LB.MACB
join LOAIMB LMB on LB.MALOAI = LMB.MALOAI
WHERE NV.TEN = 'Quang'

--Q14
SELECT NV.TEN
FROM NHANVIEN NV
WHERE NV.MANV NOT IN (SELECT PC.MANV FROM PHANCONG PC)

--Q15
SELECT DISTINCT KH.TEN
FROM KHACHHANG KH join DATCHO DC on KH.MAKH = DC.MAKH
join LICHBAY LB on DC.MACB = LB.MACB
join MAYBAY MB on LB.SOHIEU = MB.SOHIEU
join LOAIMB LMB on MB.MALOAI = LMB.MALOAI
WHERE LMB.HANGSX = 'Boeing'

--Q16
SELECT DISTINCT LB.MACB
FROM LICHBAY LB
WHERE LB.SOHIEU = 10 AND LB.MALOAI = 'B747' AND LB.MACB NOT IN (
	SELECT MACB
	FROM LICHBAY LB2
	WHERE LB2.SOHIEU <> 10 OR LB2.MALOAI <> 'B747')