use QLDT
go

--Q1
SELECT HOTEN,LUONG
FROM GIAOVIEN
WHERE PHAI=N'Nữ'

--Q3
SELECT MAGV
FROM GIAOVIEN
WHERE (HOTEN LIKE N'Nguyễn%' AND LUONG > 2000) OR (MAGV IN (SELECT TRUONGBM FROM BOMON WHERE datepart(YYYY,NGAYNHANCHUC)>1995))


--Q5
SELECT *
FROM BOMON BM join GIAOVIEN GV on BM.TRUONGBM = GV.MAGV

--Q7
SELECT DT.TENDT,DT.GVCNDT,GV.HOTEN
FROM DETAI DT join GIAOVIEN GV on DT.GVCNDT = GV.MAGV

--Q9
SELECT *
FROM THAMGIADT TGDT join GIAOVIEN GV on TGDT.MAGV=GV.MAGV
join BOMON BM on GV.MABM = BM.MABM
WHERE BM.TENBM = 'Vi sinh' AND TGDT.MADT = '006'

--Q11
SELECT GV.HOTEN, GVQL.HOTEN AS GVQL
FROM GIAOVIEN GV join GIAOVIEN GVQL on GV.GVQLCM = GVQL.MAGV

--Q13
SELECT GV.HOTEN
FROM BOMON BM join GIAOVIEN GV on BM.TRUONGBM = GV.MAGV
WHERE BM.TENBM = N'Hệ thống thông tin'

--Q15
SELECT CV.TENCV
FROM CONGVIEC CV join DETAI DT on CV.MADT = DT.MADT
join GIAOVIEN GV on DT.GVCNDT = GV.MAGV
WHERE GV.MABM = 'HTTT' AND datepart(MM,CV.NGAYBD) = 03 AND datepart(yyyy,CV.NGAYBD) = 2008

--Q17
SELECT *
FROM CONGVIEC CV
WHERE CV.NGAYBD > '01/01/2007' AND CV.NGAYBD < '08/01/2007'

--Q19
SELECT *
FROM GIAOVIEN GV
WHERE GV.MAGV IN (
	SELECT TRUONGBM
	FROM BOMON)
AND GV.MAGV IN (
	SELECT GVCNDT
	FROM DETAI)

--Q21
SELECT GV.HOTEN
FROM GIAOVIEN GV
WHERE GV.MAGV IN (
	SELECT DISTINCT TRUONGBM
	FROM BOMON)
AND GV.MAGV IN (
	SELECT DISTINCT GVCNDT
	FROM DETAI)

--Q23
SELECT MAGV
FROM GIAOVIEN GV
WHERE GV.MABM = 'HTTT'
UNION
SELECT GVCNDT
FROM DETAI DT
WHERE MADT = '001'

--Q25
SELECT *
FROM GIAOVIEN GV
WHERE GV.MAGV IN (
	SELECT DISTINCT TRUONGBM
	FROM BOMON BM)
