use QLDT
go

--Q35
SELECT DISTINCT GV.LUONG AS LUONGMAX
FROM GIAOVIEN GV
WHERE GV.LUONG >= ALL(
	SELECT GV.LUONG
	FROM GIAOVIEN GV)

--Q37
SELECT DISTINCT GV.LUONG AS LUONGMAX
FROM GIAOVIEN GV
WHERE GV.LUONG >= ALL(
	SELECT GV2.LUONG
	FROM GIAOVIEN GV2
	WHERE GV.MABM = GV2.MABM)
AND GV.MABM = 'HTTT'

--Q39
SELECT GV.HOTEN
FROM GIAOVIEN GV 
join BOMON BM on GV.MABM = BM.MABM AND BM.MAKHOA = 'CNTT'
WHERE GV.NGSINH >= ALL (
	SELECT GV.NGSINH
	FROM GIAOVIEN GV 
	join BOMON BM on GV.MABM = BM.MABM AND BM.MAKHOA = 'CNTT')

--Q41
SELECT GV.MABM, GV.LUONG
FROM GIAOVIEN GV
WHERE GV.LUONG >= ALL (
	SELECT GVDX.LUONG
	FROM GIAOVIEN GVDX
	WHERE GV.MABM = GVDX.MABM)

--Q43
SELECT DT.TENDT, GV.HOTEN
FROM DETAI DT 
join GIAOVIEN GV on DT.GVCNDT = GV.MAGV
WHERE DT.MADT NOT IN (
	SELECT DISTINCT TGDT.MADT
	FROM GIAOVIEN GV1
	join THAMGIADT TGDT on GV1.MAGV = TGDT.MAGV
	WHERE GV1.HOTEN = N'Nguyễn Hoài An')

--Q45
SELECT *
FROM GIAOVIEN GV
WHERE GV.MAGV NOT IN (
	SELECT TGDT.MAGV
	FROM THAMGIADT TGDT)

--Q47
SELECT K.TENKHOA, K.TRUONGKHOA, GV.HOTEN
FROM KHOA K
join GIAOVIEN GV on K.TRUONGKHOA = GV.MAGV
WHERE K.TRUONGKHOA IN (
	SELECT TGDT.MAGV
	FROM THAMGIADT TGDT)

--Q49
SELECT *
FROM GIAOVIEN GV
WHERE EXISTS (
	SELECT *
	FROM GIAOVIEN GV2
	join BOMON BM on GV2.MABM = BM.MABM
	WHERE BM.TENBM = N'Công nghệ phần mềm'
	AND GV.LUONG > GV2.LUONG)

--Q51
SELECT K.TENKHOA
FROM GIAOVIEN GV 
join BOMON BM on GV.MABM = BM.MABM
join KHOA K on BM.MAKHOA = K.MAKHOA
GROUP BY K.MAKHOA, K.TENKHOA
HAVING COUNT(*) >= ALL(
	SELECT COUNT(*)
	FROM GIAOVIEN GV 
	join BOMON BM on GV.MABM = BM.MABM
	join KHOA K on BM.MAKHOA = K.MAKHOA
	GROUP BY K.MAKHOA, K.TENKHOA)

--Q53
SELECT BM.MABM, COUNT(*)
FROM GIAOVIEN GV 
join BOMON BM on GV.MABM = BM.MABM
GROUP BY BM.MABM
HAVING COUNT(*) >= ALL(
	SELECT COUNT(*)
	FROM GIAOVIEN GV 
	join BOMON BM on GV.MABM = BM.MABM
	GROUP BY BM.MABM)

--Q55
SELECT GV.HOTEN
FROM GIAOVIEN GV
join THAMGIADT TGDT on GV.MAGV = TGDT.MAGV AND GV.MABM = 'HTTT'
GROUP BY GV.MAGV, GV.HOTEN
HAVING COUNT(DISTINCT TGDT.MADT) >= ALL(
	SELECT COUNT(DISTINCT TGDT.MADT)
	FROM GIAOVIEN GV
	join THAMGIADT TGDT on GV.MAGV = TGDT.MAGV AND GV.MABM = 'HTTT'
	GROUP BY GV.MAGV, GV.HOTEN)

--Q57
SELECT GV.HOTEN
FROM BOMON BM 
join GIAOVIEN GV on BM.TRUONGBM = GV.MAGV
join DETAI DT on DT.GVCNDT = BM.TRUONGBM
GROUP BY GV.MAGV, GV.HOTEN
HAVING COUNT(*) >= ALL(
	SELECT COUNT(*)
	FROM BOMON BM 
	join GIAOVIEN GV on BM.TRUONGBM = GV.MAGV
	join DETAI DT on DT.GVCNDT = BM.TRUONGBM
	GROUP BY GV.MAGV, GV.HOTEN)