----QLDT----
use QLDT
go
--Q58
--EXCEPT
SELECT DISTINCT GV.HOTEN
FROM GIAOVIEN GV
JOIN THAMGIADT TGDT ON GV.MAGV = TGDT.MAGV
WHERE NOT EXISTS (
	SELECT MACD FROM CHUDE
	EXCEPT
	(
		SELECT CD2.MACD FROM CHUDE CD2
		JOIN DETAI DT2 ON DT2.MACD = CD2.MACD
		JOIN THAMGIADT TGDT2 ON TGDT2.MADT = DT2.MADT
		WHERE TGDT2.MAGV = TGDT.MAGV
	)
)
--NOT EXISTS
SELECT DISTINCT GV.HOTEN
FROM GIAOVIEN GV
JOIN THAMGIADT TGDT ON GV.MAGV = TGDT.MAGV
WHERE NOT EXISTS (
	SELECT CD1.MACD FROM CHUDE CD1
	WHERE NOT EXISTS (
		SELECT CD2.MACD FROM CHUDE CD2
		JOIN DETAI DT2 ON DT2.MACD = CD2.MACD
		JOIN THAMGIADT TGDT2 ON TGDT2.MADT = DT2.MADT
		WHERE TGDT2.MAGV = TGDT.MAGV AND CD2.MACD = CD1.MACD))
--COUNT
SELECT DISTINCT GV.HOTEN
FROM GIAOVIEN GV
JOIN THAMGIADT TGDT ON GV.MAGV = TGDT.MAGV
JOIN DETAI DT ON TGDT.MADT = DT.MADT
GROUP BY GV.MAGV, GV.HOTEN
HAVING COUNT(DISTINCT DT.MACD) = (
	SELECT COUNT(CD.MACD)
	FROM CHUDE CD)

--Q60
--EXCEPT
SELECT DT.TENDT
FROM DETAI DT
WHERE NOT EXISTS (
	SELECT GV1.MAGV
	FROM GIAOVIEN GV1
	JOIN BOMON BM ON GV1.MABM = BM.MABM
	WHERE BM.TENBM = N'Hệ thống thông tin'
	EXCEPT (
		SELECT GV2.MAGV
		FROM GIAOVIEN GV2
		JOIN THAMGIADT TGDT2 ON TGDT2.MAGV = GV2.MAGV
		WHERE TGDT2.MADT = DT.MADT)
)
--NOT EXISTS
SELECT DT.TENDT
FROM DETAI DT
WHERE NOT EXISTS (
	SELECT GV1.MAGV
	FROM GIAOVIEN GV1
	JOIN BOMON BM ON GV1.MABM = BM.MABM
	WHERE BM.TENBM = N'Hệ thống thông tin'
	AND NOT EXISTS (
		SELECT GV2.MAGV
		FROM GIAOVIEN GV2
		JOIN THAMGIADT TGDT2 ON TGDT2.MAGV = GV2.MAGV
		WHERE TGDT2.MADT = DT.MADT AND GV2.MAGV = GV1.MAGV)
)
--COUNT
SELECT DT.TENDT
FROM GIAOVIEN GV
JOIN THAMGIADT TGDT ON TGDT.MAGV = GV.MAGV
JOIN DETAI DT ON TGDT.MADT = DT.MADT
JOIN BOMON BM ON GV.MABM = BM.MABM
WHERE BM.TENBM = N'Hệ thống thông tin'
GROUP BY TGDT.MADT, DT.TENDT
HAVING COUNT(DISTINCT GV.MAGV) = (
	SELECT COUNT(*)
	FROM GIAOVIEN GV2
	JOIN BOMON BM2 ON GV2.MABM = BM2.MABM
	WHERE BM2.TENBM = N'Hệ thống thông tin')

--Q62
--EXCEPT
SELECT GV.HOTEN
FROM GIAOVIEN GV
WHERE NOT EXISTS (
	SELECT DISTINCT TGDT.MADT
	FROM GIAOVIEN GV1
	JOIN THAMGIADT TGDT ON GV1.MAGV = TGDT.MAGV
	WHERE GV1.HOTEN = N'Trần Trà Hương'
	EXCEPT (
		SELECT DISTINCT TGDT2.MADT
		FROM GIAOVIEN GV2
		JOIN THAMGIADT TGDT2 ON GV2.MAGV = TGDT2.MAGV
		WHERE GV2.MAGV = GV.MAGV))
AND GV.HOTEN <> N'Trần Trà Hương'
--NOT EXISTS
SELECT GV.HOTEN
FROM GIAOVIEN GV
WHERE NOT EXISTS (
	SELECT DISTINCT TGDT.MADT
	FROM GIAOVIEN GV1
	JOIN THAMGIADT TGDT ON GV1.MAGV = TGDT.MAGV
	WHERE GV1.HOTEN = N'Trần Trà Hương'
	AND NOT EXISTS (
		SELECT DISTINCT TGDT2.MADT
		FROM GIAOVIEN GV2
		JOIN THAMGIADT TGDT2 ON GV2.MAGV = TGDT2.MAGV
		WHERE GV2.MAGV = GV.MAGV AND TGDT2.MADT = TGDT.MADT))
AND GV.HOTEN <> N'Trần Trà Hương'
--COUNT: khong lam duoc

--Q64
--EXCEPT
SELECT GV.HOTEN
FROM GIAOVIEN GV
WHERE NOT EXISTS (
	SELECT CV.MADT, CV.SOTT
	FROM CONGVIEC CV
	WHERE CV.MADT = '006'
	EXCEPT (
		SELECT TGDT.MADT, TGDT.STT
		FROM THAMGIADT TGDT
		WHERE TGDT.MADT = '006' AND TGDT.MAGV = GV.MAGV)
)
--NOT EXISTS
SELECT GV.HOTEN
FROM GIAOVIEN GV
WHERE NOT EXISTS (
	SELECT CV.MADT, CV.SOTT
	FROM CONGVIEC CV
	WHERE CV.MADT = '006'
	AND NOT EXISTS (
		SELECT TGDT.MADT, TGDT.STT
		FROM THAMGIADT TGDT
		WHERE TGDT.MADT = '006' AND TGDT.MAGV = GV.MAGV AND CV.MADT = TGDT.MADT AND CV.SOTT = TGDT.STT)
)
--COUNT
SELECT GV.HOTEN
FROM GIAOVIEN GV
JOIN THAMGIADT TGDT ON GV.MAGV = TGDT.MAGV
WHERE TGDT.MADT = '006'
GROUP BY GV.HOTEN, GV.MAGV
HAVING COUNT(DISTINCT TGDT.STT) = (
	SELECT COUNT(*)
	FROM CONGVIEC CV2
	WHERE CV2.MADT = '006'
)

--Q66
--EXCEPT
SELECT GV.HOTEN
FROM GIAOVIEN GV
WHERE NOT EXISTS (
	SELECT DT.MADT
	FROM DETAI DT
	JOIN GIAOVIEN GV1 ON DT.GVCNDT = GV1.MAGV
	WHERE GV1.HOTEN = N'Trần Trà Hương'
	EXCEPT (
		SELECT TGDT2.MADT
		FROM THAMGIADT TGDT2
		JOIN GIAOVIEN GV2 ON TGDT2.MAGV = GV2.MAGV
		WHERE GV2.MAGV = GV.MAGV))
--NOT EXISTS
SELECT GV.HOTEN
FROM GIAOVIEN GV
WHERE NOT EXISTS (
	SELECT DT.MADT
	FROM DETAI DT
	JOIN GIAOVIEN GV1 ON DT.GVCNDT = GV1.MAGV
	WHERE GV1.HOTEN = N'Trần Trà Hương'
	AND NOT EXISTS (
		SELECT TGDT2.MADT
		FROM THAMGIADT TGDT2
		JOIN GIAOVIEN GV2 ON TGDT2.MAGV = GV2.MAGV
		WHERE GV2.MAGV = GV.MAGV AND TGDT2.MADT = DT.MADT))
--COUNT: khong lam duoc

--Q68
--EXCEPT
SELECT GV.HOTEN
FROM GIAOVIEN GV
WHERE NOT EXISTS (
	SELECT CV.MADT, CV.SOTT
	FROM CONGVIEC CV
	JOIN DETAI DT ON CV.MADT = DT.MADT
	WHERE DT.TENDT = N'Nghiên cứu tế bào gốc'
	EXCEPT (
		SELECT TGDT.MADT, TGDT.STT
		FROM THAMGIADT TGDT
		WHERE TGDT.MAGV = GV.MAGV))
--NOT EXISTS
SELECT GV.HOTEN
FROM GIAOVIEN GV
WHERE NOT EXISTS (
	SELECT CV.MADT, CV.SOTT
	FROM CONGVIEC CV
	JOIN DETAI DT ON CV.MADT = DT.MADT
	WHERE DT.TENDT = N'Nghiên cứu tế bào gốc'
	AND NOT EXISTS (
		SELECT TGDT.MADT, TGDT.STT
		FROM THAMGIADT TGDT
		WHERE TGDT.MAGV = GV.MAGV AND TGDT.MADT = DT.MADT AND TGDT.STT = CV.SOTT))
--COUNT
SELECT GV.HOTEN
FROM GIAOVIEN GV
JOIN THAMGIADT TGDT ON GV.MAGV = TGDT.MAGV
JOIN DETAI DT ON TGDT.MADT = DT.MADT
WHERE DT.TENDT = N'Nghiên cứu tế bào gốc'
GROUP BY GV.MAGV, GV.HOTEN
HAVING COUNT(DISTINCT TGDT.STT) = (
	SELECT COUNT(DISTINCT CV.SOTT)
	FROM CONGVIEC CV
	JOIN DETAI DT2 ON CV.MADT = DT2.MADT
	WHERE DT2.TENDT = N'Nghiên cứu tế bào gốc')

--Q70
--EXCEPT
SELECT DT.TENDT
FROM DETAI DT
WHERE NOT EXISTS (
	SELECT GV.MAGV
	FROM GIAOVIEN GV
	JOIN BOMON BM ON GV.MABM = BM.MABM
	JOIN KHOA K ON BM.MAKHOA = K.MAKHOA
	WHERE K.TENKHOA = N'Sinh học'
	EXCEPT (
		SELECT GV2.MAGV
		FROM GIAOVIEN GV2
		JOIN THAMGIADT TGDT ON GV2.MAGV = TGDT.MAGV
		WHERE DT.MADT = TGDT.MADT
	))
--NOT EXISTS
SELECT DT.TENDT
FROM DETAI DT
WHERE NOT EXISTS (
	SELECT GV.MAGV
	FROM GIAOVIEN GV
	JOIN BOMON BM ON GV.MABM = BM.MABM
	JOIN KHOA K ON BM.MAKHOA = K.MAKHOA
	WHERE K.TENKHOA = N'Sinh học'
	AND NOT EXISTS (
		SELECT GV2.MAGV
		FROM GIAOVIEN GV2
		JOIN THAMGIADT TGDT ON GV2.MAGV = TGDT.MAGV
		WHERE DT.MADT = TGDT.MADT AND GV2.MAGV = GV.MAGV
	))
--COUNT
SELECT DT.TENDT
FROM DETAI DT
JOIN THAMGIADT TGDT ON DT.MADT = TGDT.MADT
JOIN GIAOVIEN GV ON TGDT.MAGV = GV.MAGV
JOIN BOMON BM ON GV.MABM = BM.MABM
JOIN KHOA K ON BM.MAKHOA = K.MAKHOA
WHERE K.TENKHOA = N'Sinh học'
GROUP BY DT.MADT, DT.TENDT
HAVING COUNT(DISTINCT TGDT.MAGV) = (
	SELECT COUNT(*)
	FROM GIAOVIEN GV2
	JOIN BOMON BM2 ON GV2.MABM = BM2.MABM
	JOIN KHOA K2 ON BM2.MAKHOA = K2.MAKHOA
	WHERE K2.TENKHOA = N'Sinh học')

--Q72
--EXCEPT
SELECT GV.MAGV, GV.HOTEN, BM.TENBM, NQL.HOTEN AS TENNQL
FROM GIAOVIEN GV
LEFT JOIN GIAOVIEN NQL ON GV.GVQLCM = NQL.MAGV
LEFT JOIN BOMON BM ON GV.MABM = BM.MABM
WHERE NOT EXISTS (
	SELECT DT.MADT
	FROM DETAI DT
	JOIN CHUDE CD ON DT.MACD = CD.MACD
	WHERE CD.TENCD = N'Nghiên cứu phát triển'
	EXCEPT (
		SELECT DT2.MADT
		FROM DETAI DT2
		JOIN THAMGIADT TGDT ON DT2.MADT = TGDT.MADT
		JOIN CHUDE CD2 ON DT2.MACD = CD2.MACD
		WHERE GV.MAGV = TGDT.MAGV))
--NOT EXISTS
SELECT GV.MAGV, GV.HOTEN, BM.TENBM, NQL.HOTEN AS TENNQL
FROM GIAOVIEN GV
LEFT JOIN GIAOVIEN NQL ON GV.GVQLCM = NQL.MAGV
LEFT JOIN BOMON BM ON GV.MABM = BM.MABM
WHERE NOT EXISTS (
	SELECT DT.MADT
	FROM DETAI DT
	JOIN CHUDE CD ON DT.MACD = CD.MACD
	WHERE CD.TENCD = N'Nghiên cứu phát triển'
	AND NOT EXISTS (
		SELECT DT2.MADT
		FROM DETAI DT2
		JOIN THAMGIADT TGDT ON DT2.MADT = TGDT.MADT
		JOIN CHUDE CD2 ON DT2.MACD = CD2.MACD
		WHERE GV.MAGV = TGDT.MAGV AND DT2.MADT = DT.MADT))
--COUNT
SELECT GV.MAGV, GV.HOTEN, BM.TENBM, NQL.HOTEN AS TENNQL
FROM GIAOVIEN GV
LEFT JOIN GIAOVIEN NQL ON GV.GVQLCM = NQL.MAGV
LEFT JOIN BOMON BM ON GV.MABM = BM.MABM
JOIN THAMGIADT TGDT ON TGDT.MAGV = GV.MAGV
JOIN DETAI DT ON TGDT.MADT = DT.MADT
JOIN CHUDE CD ON DT.MACD = CD.MACD
WHERE CD.TENCD = N'Nghiên cứu phát triển'
GROUP BY GV.MAGV, GV.HOTEN, BM.TENBM, NQL.HOTEN
HAVING COUNT(DISTINCT DT.MADT) = (
	SELECT COUNT (DISTINCT DT2.MADT)
	FROM DETAI DT2
	JOIN CHUDE CD2 ON DT2.MACD = CD2.MACD
	WHERE CD2.TENCD = N'Nghiên cứu phát triển')