------QLCB------
use QLCB
go

--Q17
SELECT CB.SBDEN, COUNT(*) AS SOLUONG
FROM CHUYENBAY CB
GROUP BY CB.SBDEN
ORDER BY CB.SBDEN ASC

--Q18
SELECT CB.SBDI, COUNT(*) AS SOLUONG
FROM CHUYENBAY CB
GROUP BY CB.SBDI
ORDER BY CB.SBDI ASC

--Q19
SELECT CB.SBDI, LB.NGAYDI, COUNT(*) AS SOLUONG
FROM CHUYENBAY CB 
join LICHBAY LB on CB.MACB = LB.MACB
GROUP BY CB.SBDI, LB.NGAYDI

--Q20
SELECT CB.SBDEN, LB.NGAYDI, COUNT(*) AS SOLUONG
FROM CHUYENBAY CB 
join LICHBAY LB on CB.MACB = LB.MACB
GROUP BY CB.SBDEN, LB.NGAYDI

--Q21
SELECT LB.MACB, LB.NGAYDI, COUNT(DISTINCT NV.MANV) AS SLKPC
FROM LICHBAY LB 
left join PHANCONG PC on LB.MACB = PC.MACB AND LB.NGAYDI = PC.NGAYDI
left join NHANVIEN NV on PC.MANV = NV.MANV AND NV.LOAINV = 0
GROUP BY LB.MACB, LB.NGAYDI

--Q22
SELECT CB.SBDI, LB.NGAYDI, COUNT(*) AS SL
FROM CHUYENBAY CB 
join LICHBAY LB on CB.MACB = LB.MACB
GROUP BY CB.SBDI, LB.NGAYDI
HAVING CB.SBDI = 'MIA' AND NGAYDI = '11/01/2000'

--Q23
SELECT LB.MACB, LB.NGAYDI, COUNT(DISTINCT PC.MANV) AS SLPC
FROM LICHBAY LB 
left join PHANCONG PC on LB.MACB = PC.MACB AND LB.NGAYDI = PC.NGAYDI
GROUP BY LB.MACB, LB.NGAYDI
ORDER BY SLPC DESC

--Q24
SELECT LB.MACB, LB.NGAYDI, COUNT(DISTINCT MAKH) AS SLDC
FROM LICHBAY LB 
left join DATCHO DC on LB.MACB = DC.MACB AND LB.NGAYDI = DC.NGAYDI
GROUP BY LB.MACB, LB.NGAYDI
ORDER BY SLDC DESC

--Q25
SELECT PC.MACB, PC.NGAYDI, SUM(NV.LUONG) AS TONGLUONG
FROM PHANCONG PC
join NHANVIEN NV on PC.MANV = NV.MANV
GROUP BY PC.MACB, PC.NGAYDI
ORDER BY TONGLUONG

--Q26
SELECT AVG(NV.LUONG) AS LKPC
FROM NHANVIEN NV
WHERE NV.LOAINV = 0

--Q27
SELECT AVG(NV.LUONG) AS LPC
FROM NHANVIEN NV
WHERE NV.LOAINV = 1

--Q28
SELECT LMB.MALOAI, COUNT(*) AS SLCB
FROM LOAIMB LMB 
join LICHBAY LB on LMB.MALOAI = LB.MALOAI
join CHUYENBAY CB on LB.MACB = CB.MACB
WHERE CB.SBDEN = 'ORD'
GROUP BY LMB.MALOAI

--Q29
SELECT CB.SBDI, COUNT(*) AS SLCB
FROM CHUYENBAY CB
WHERE datepart(hour, CB.GIODI) >= 10 AND datepart(hour, CB.GIODI) <= 22
GROUP BY CB.SBDI
HAVING COUNT(*) > 2

--Q30
SELECT DISTINCT NV.TEN
FROM PHANCONG PC 
join NHANVIEN NV on PC.MANV = NV.MANV 
GROUP BY PC.MANV, NV.TEN, PC.NGAYDI
HAVING COUNT(*) >= 2

--Q31
SELECT DISTINCT LB.MACB, LB.NGAYDI
FROM DATCHO DC 
join  LICHBAY LB on DC.MACB = LB.MACB AND DC.NGAYDI = LB.NGAYDI
GROUP BY LB.MACB, LB.NGAYDI
HAVING COUNT(*) < 3

--Q32
SELECT LB.SOHIEU, LB.MALOAI, COUNT(*) AS SLCB
FROM LICHBAY LB 
join PHANCONG PC on LB.MACB = PC.MACB AND LB.NGAYDI = PC.NGAYDI
WHERE PC.MANV = '1001'
GROUP BY LB.SOHIEU, LB.MALOAI
HAVING COUNT(*) > 2

--Q33
SELECT LMB.HANGSX, COUNT(*) AS SLMB
FROM LOAIMB LMB
GROUP BY LMB.HANGSX

------QLDT------
use QLDT
go

--Q27
SELECT COUNT(*) AS SOLUONG, SUM(GV.LUONG) AS TONGLUONG
FROM GIAOVIEN GV

--Q28
SELECT BM.MABM, COUNT(*) AS SOLUONG, SUM(GV.LUONG) AS TONGLUONG
FROM BOMON BM 
join GIAOVIEN GV on BM.MABM = GV.MABM
GROUP BY BM.MABM

--Q29
SELECT CD.TENCD, COUNT(*) AS SOLUONG
FROM CHUDE CD 
join DETAI DT on CD.MACD = DT.MACD
GROUP BY CD.MACD, CD.TENCD

--Q30
SELECT GV.HOTEN, COUNT(DISTINCT TGDT.MADT) AS SOLUONG
FROM THAMGIADT TGDT join GIAOVIEN GV on TGDT.MAGV = GV.MAGV
GROUP BY TGDT.MAGV, GV.HOTEN

--Q31
SELECT GV.HOTEN, COUNT(*) AS SOLUONG
FROM DETAI DT join GIAOVIEN GV on DT.GVCNDT = GV.MAGV
GROUP BY DT.GVCNDT, GV.HOTEN

--Q32
SELECT GV.HOTEN, COUNT(NT.TEN) AS SONT
FROM GIAOVIEN GV left join NGUOITHAN NT on GV.MAGV = NT.MAGV
GROUP BY GV.MAGV, GV.HOTEN

--Q33
SELECT GV.HOTEN, COUNT(DISTINCT TGDT.MADT) AS SOLUONG
FROM THAMGIADT TGDT join GIAOVIEN GV on TGDT.MAGV = GV.MAGV
GROUP BY TGDT.MAGV, GV.HOTEN
HAVING COUNT(DISTINCT TGDT.MADT) >= 3

--Q34
SELECT COUNT(DISTINCT TGDT.MAGV) AS SLGV
FROM DETAI DT left join THAMGIADT TGDT on DT.MADT = TGDT.MADT
WHERE DT.TENDT = N'Ứng dụng hóa học xanh'
GROUP BY DT.MADT, DT.TENDT