CREATE DATABASE QLBaiHat
USE QLBaiHat
GO

CREATE TABLE BAIHAT (
	TheLoai nchar(10),
	IDBaiHat nchar(10),
	TenBaiHat nchar(30),
	TacGia numeric
	PRIMARY KEY (TheLoai, IDBaiHat)
)

CREATE TABLE THELOAI (
	IDTheLoai nchar(10),
	Ten nchar(30),
	BaiHatTieuBieu nchar(10),
	TheLoaiCha nchar(10)
	PRIMARY KEY (IDTheLoai)
)

CREATE TABLE TACGIA (
	IDTacGia numeric,
	HoTen nchar(30),
	TheLoai nchar(10),
	BaiHatTieuBieu nchar(10)
	PRIMARY KEY (IDTacGia)
)

ALTER TABLE BAIHAT
ADD CONSTRAINT FK_BHTheLoai_TLIDTheLoai
FOREIGN KEY (TheLoai)
REFERENCES THELOAI(IDTheLoai)

ALTER TABLE BAIHAT
ADD CONSTRAINT FK_BHTacGia_TGIDTacGia
FOREIGN KEY (TacGia)
REFERENCES TACGIA(IDTacGia)

ALTER TABLE THELOAI
ADD CONSTRAINT FK_TLBaiHatTieuBieu_BHIDBaiHat
FOREIGN KEY (IDTheLoai, BaiHatTieuBieu)
REFERENCES BAIHAT(TheLoai, IDBaiHat)

ALTER TABLE THELOAI
ADD CONSTRAINT FK_TLTheLoaiCha_TLIDTheLoai
FOREIGN KEY (TheLoaiCha)
REFERENCES THELOAI(IDTheLoai)

ALTER TABLE TACGIA
ADD CONSTRAINT FK_TGBaiHatTieuBieu_BHIDBaiHat
FOREIGN KEY (TheLoai, BaiHatTieuBieu)
REFERENCES BAIHAT(TheLoai, IDBaiHat)

INSERT INTO THELOAI VALUES ('TL01', N'Nhạc trữ tình', NULL, NULL)
INSERT INTO THELOAI VALUES ('TL02', N'Nhạc cách mạng', NULL, NULL)
INSERT INTO THELOAI VALUES ('TL00', N'Nhạc Việt Nam', NULL, NULL)

UPDATE THELOAI
SET TheLoaiCha = 'TL00'
WHERE IDTheLoai = 'TL01' OR IDTheLoai = 'TL02'

INSERT INTO BAIHAT VALUES ('TL01', 'BH01', N'Ngẫu hứng lý qua cấu', NULL)
INSERT INTO BAIHAT VALUES ('TL01', 'BH02', N'Chuyến đò quê hương', NULL)
INSERT INTO BAIHAT VALUES ('TL02', 'BH01', N'Du kích sông thao', NULL)
INSERT INTO BAIHAT VALUES ('TL02', 'BH02', N'Sợi nhớ sợi thương', NULL)

UPDATE THELOAI
SET BaiHatTieuBieu = 'BH01'
WHERE IDTheLoai = 'TL01'

UPDATE THELOAI
SET BaiHatTieuBieu = 'BH02'
WHERE IDTheLoai = 'TL02'

INSERT INTO TACGIA VALUES (1, N'Trần Tiến', 'TL01','BH01')
INSERT INTO TACGIA VALUES (2, N'Đỗ Nhuận', 'TL02', 'BH01')
INSERT INTO TACGIA VALUES (3, N'Phan Huỳnh Điểu', 'TL02', 'BH02')
INSERT INTO TACGIA VALUES (4, N'Vi Nhật Tảo', 'TL01', 'BH02')

UPDATE BAIHAT
SET TacGia = 1
WHERE TheLoai = 'TL01' AND IDBaiHat = 'BH01'

UPDATE BAIHAT
SET TacGia = 4
WHERE TheLoai = 'TL01' AND IDBaiHat = 'BH02'

UPDATE BAIHAT
SET TacGia = 2
WHERE TheLoai = 'TL02' AND IDBaiHat = 'BH01'

UPDATE BAIHAT
SET TacGia = 3
WHERE TheLoai = 'TL02' AND IDBaiHat = 'BH02'
